### ISSUE TITLE
Set a Home link on the banner

### ISSUE THREAD

**Issue by erwanosouf** [Majorgrafismz/Majorgrafismz.github.io#1]
Il faudrait pouvoir revenir a l'accueil du site en cliquant sur la bannière
Chanmé ton site !

**Comment by Majorgrafismz** [comment]
**ok je prends note ! ahahahah !** MERCI !

**Comment by Majorgrafismz** [comment]
DONE ! ;)

**Comment by erwanosouf** [comment]
Pour info, tu peux fermer automatiquement les tickets en mettant "fix #1" dans ton message de commit.
Un fois que tu push, ca ferme automatiquement l'issue n°1.
